language: cpp

matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx
      osx_image: xcode11.3

script:
  - mkdir build && cd build
  - cmake .. -DFSAL_TESTS=ON
  - make
  - ./tests

branches:
  only:
    - master

notifications:
  email: false
 
